# Generated by Django 5.1.3 on 2024-11-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="detail",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="summary",
            field=models.CharField(max_length=200),
        ),
    ]
