# Generated by Django 5.1.3 on 2024-11-28 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_detail_alter_job_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="detail",
        ),
    ]
