# Generated by Django 5.1.3 on 2024-11-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_remove_job_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="summary",
            field=models.CharField(max_length=400),
        ),
    ]
