# Generated by Django 5.1.3 on 2024-11-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_job_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="detail",
            field=models.TextField(),
        ),
    ]
