# Generated by Django 5.1.3 on 2024-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_job_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
